# This is a basic workflow to help you get started with Actions

name: Practice

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - staging #branch name



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CI: false 
      PROJECT_PATH: keystone-database-project-restructure #name of the react project
    defaults:
      run:
        working-directory: keystone-database-project-restructure #name of the react project
    steps:  
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: 
        node-version: 12
    - run: echo ls *
    - run: npm install --prefix 
    - run: npm run build --prefix
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}